name: pipeline

on:
  push

env:
  BASE_TAG: user/xrootd-cmstfc:base
  LATEST_TAG: ghcr.io/guyzsarun/xrootd-cmsjson:latest

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        version: ["almalinux:8", "almalinux:9"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.rpm
          tags: ${{ env.BASE_TAG }}
          build-args: |
            IMAGE=${{ matrix.version }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Unit test
        run: |
          docker run --rm ${{ env.BASE_TAG }} python3 -m pytest -v

  # test-json:
  #   name: Test JSON Conversion
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out Git repository
  #       uses: actions/checkout@v2

  #     - uses: docker/setup-buildx-action@v2

  #     - name: Build Docker image
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         file: docker/Dockerfile
  #         tags: ${{ env.BASE_TAG }}
  #         load: true
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max

  #     - name: Unit test
  #       run: |
  #         docker run --rm ${{ env.BASE_TAG }} python3 -m pytest -v

  # test-rpm:
  #   name: Package RPM
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out Git repository
  #       uses: actions/checkout@v2

  #     - uses: docker/setup-buildx-action@v2

  #     - name: Build Docker image
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         file: docker/Dockerfile.rpm
  #         load: true
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max

